### ISSUE TITLE
Cannot rename a file in a torrent

### ISSUE THREAD

**Issue by CakesTwix** [trim21/transmission-rpc#373]
# Description

Made a script that automatically compares torrents for new changes and downloads and rename in parallel.

## Environment

- language version: Python 3.11
- app/lib/repo version: 4.3.0 and latest
- Transmission: 4.1.0-dev

## How to reproduce

https://github.com/CakesTwix/Toloka2Tranmission/blob/main/toloka2transmission/utils/transmission.py#L61

## Expectations

Successful renaming as when adding a torrent

## Actual result

Classroom of the Elite/Episode S3E01.mkv Episode S3E1.mkv
DEBUG:urllib3.connectionpool:http://192.168.1.9:9091 "POST /transmission/rpc HTTP/1.1" 409 581
DEBUG:urllib3.connectionpool:http://192.168.1.9:9091 "POST /transmission/rpc HTTP/1.1" 200 132
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/media/HDD/Toloka2Transmission/toloka2transmission/__main__.py", line 118, in <module>
    update(title, args.force)
  File "/media/HDD/Toloka2Transmission/toloka2transmission/utils/transmission.py", line 61, in update
    TransmissionClient.rename_torrent_path(
  File "/home/cakestwix/.local/lib/python3.11/site-packages/transmission_rpc/client.py", line 804, in rename_torrent_path
    result = self._request(
             ^^^^^^^^^^^^^^
  File "/home/cakestwix/.local/lib/python3.11/site-packages/transmission_rpc/client.py", line 261, in _request
    raise TransmissionError(
transmission_rpc.error.TransmissionError: Query failed with result "Invalid argument".

**Comment by CakesTwix** [comment]
My problem. Fixed
